name: dressing_room
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.9.0
  path_provider: ^2.0.8
  image_picker: ^0.8.4+3
  image_cropper: ^1.4.1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.0
  firebase_storage: ^11.2.1
  uuid: ^3.0.7
  http: ^1.1.2
  dots_indicator: ^3.0.0
  intl: ^0.18.1
  flutter_svg: ^2.0.10+1
  provider: ^6.0.5
  rxdart: ^0.27.7
  cloud_firestore: ^4.7.0
  flutter_background_service: ^2.4.6
  flip_card: ^0.7.0
  rename_app: ^1.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_card_swiper: ^6.1.0
  flutter_icon_shadow: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf
