name: dressing_room
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.9.0
  animate_do: ^2.0.0
  line_icons: ^2.0.3
  two_dimensional_scrollables: ^0.0.5
  flutter_slidable: ^3.0.1
  flip_card: ^0.7.0
  gap: ^3.0.1
  image_picker: ^0.8.4+3
  http: ^1.1.2
  path_provider: ^2.0.8
  permission_handler: ^11.1.0
  google_fonts: 5.1.0
  flutter_speed_dial: ^7.0.0
  sliding_up_panel: ^2.0.0+1
  image_cropper: ^1.4.1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.0
  flutter_rating_bar: ^4.0.1
  firebase_storage: ^11.2.1
  uuid: ^3.0.7
  dots_indicator: ^3.0.0
  flutter_box_transform: ^0.4.2
  intl: ^0.18.1
  provider: ^6.0.5
  custom_image_crop: ^0.0.13
  rxdart: ^0.27.7
  cloud_firestore: ^4.7.0
  icons_launcher: ^2.1.7
  flutter_background_service: ^2.4.6
  receive_sharing_intent: ^1.6.7
  flutter_card_swiper: ^7.0.0
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  webview_flutter: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

icons_launcher:
  image_path: "assets/LOGO-ICON.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Regular.ttf

  assets:
    - assets/
